version: "3.8"

services:
  
  redis:
    container_name: redis
    image: redis:alpine3.19
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=%Kl_@01Bn/M

volumes:
  redis_data: